Post release to telegram channel

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -145,6 +145,46 @@ jobs:
           POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
           curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "message_thread_id=26772" --data-urlencode "chat_id=${CHAT_ID}" "$POST"
 
+      - name: Report to Telegram Channel
+        env:
+            TG_TOKEN: ${{ secrets.TG_TOKEN }}
+            CHAT_ID: ${{ secrets.CHAT_ID }}
+        if: env.TG_TOKEN != null
+        run: |
+            cd build || { echo "build folder not found"; exit 1; }
+  
+            NL=$'\n'
+            APKS=""
+            MODULES=""
+            CHAT_ID=${CHAT_ID}
+            for OUTPUT in *; do
+              DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+              if [[ $OUTPUT = *.apk ]]; then
+                APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
+              elif [[ $OUTPUT = *.zip ]]; then
+                MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
+              fi
+            done
+            MODULES=${MODULES#"$NL"}
+            APKS=${APKS#"$NL"}
+  
+            BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d;' ../build.md)"
+            MSG="*New build!*
+  
+            ${BODY}
+            *[arm64-v8a]*
+            *▼ Download Links:*
+            Modules:
+            ${MODULES}
+  
+            APKs:
+            ${APKS}
+            "
+            echo "'$MSG'"
+            MSG=${MSG:0:9450}
+            POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+            curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
+
       - uses: stefanzweifel/git-auto-commit-action@v5.0.1
         with:
           branch: update
